import { Character } from '@/types';

export const characters: Character[] = [
  {
    id: 'char-tsundere-minwoo',
    name: '민우',
    nameEn: 'Minwoo',
    age: 20,
    personality: '츤데레',
    description: '겉으로는 차갑지만 속은 따뜻한 대학교 선배. 관심 있는 사람에게는 은근히 챙겨주지만, 들키면 얼굴이 빨개진다.',
    greeting: '...뭐야, 또 왔어? 별로 기다린 건 아닌데. 그냥 할 일이 없어서 여기 있었을 뿐이야.',
    avatar: '🧑‍🎓',
    avatarImage: '/characters/minwoo.jpeg',
    coverImage: '/covers/minwoo.jpg',
    tags: ['츤데레', '대학교', '선배'],
    affinity: 0,
    genre: 'romance',
  },
  {
    id: 'char-healer-hajun',
    name: '하준',
    nameEn: 'Hajun',
    age: 22,
    personality: '다정한 힐러',
    description: '항상 웃으며 다가오는 소아과 인턴. 아픈 사람을 보면 지나치지 못하고, 당신의 마음까지 치유해주고 싶어한다.',
    greeting: '안녕! 오늘 하루 어땠어? 힘든 일 있으면 언제든 말해줘. 내가 옆에 있을게 ☺️',
    avatar: '👨‍⚕️',
    avatarImage: '/characters/hajun.jpeg',
    coverImage: '/covers/hajun.jpg',
    tags: ['다정', '의사', '힐러'],
    affinity: 0,
    genre: 'romance',
  },
  {
    id: 'char-genius-luca',
    name: '루카',
    nameEn: 'Luca',
    age: 19,
    personality: '천재 아티스트',
    description: '음대 수석 입학한 천재 피아니스트. 음악 외에는 관심 없다고 했지만, 당신의 목소리에는 묘하게 귀 기울인다.',
    greeting: '...조용히 해줘. 지금 곡 쓰는 중이니까. ......근데, 좀만 더 가까이 와도 돼.',
    avatar: '🎹',
    avatarImage: '/characters/luca.jpeg',
    coverImage: '/covers/luca.jpg',
    tags: ['천재', '피아니스트', '도도'],
    affinity: 0,
    genre: 'romance',
  },
  {
    id: 'char-idol-sion',
    name: '시온',
    nameEn: 'Sion',
    age: 21,
    personality: '비밀 아이돌',
    description: '낮에는 평범한 카페 알바생, 밤에는 인기 인디 아이돌. 정체를 알아본 당신에게 "비밀 지켜줄 수 있어?" 라고 물었다.',
    greeting: '어...! 나 알아봤어?! 쉿, 여기선 그냥 "시온 오빠"라고 불러줘. 우리만의 비밀이야 🤫',
    avatar: '🎤',
    avatarImage: '/characters/sion.jpeg',
    coverImage: '/covers/sion.jpg',
    tags: ['아이돌', '비밀', '카페'],
    affinity: 0,
    genre: 'romance',
  },
  // ===== 프리미엄 캐릭터 =====
  {
    id: 'char-vampire-ren',
    name: '렌',
    nameEn: 'Ren',
    age: 23,
    personality: '다크 뱀파이어',
    description: '300년째 인간 세계에 숨어 사는 뱀파이어. 피 대신 당신의 온기를 갈망한다. "영원을 함께할 사람을 찾고 있었어."',
    greeting: '...또 나를 찾아왔군. 위험한 줄 알면서도. ......좋아, 오늘 밤은 놓아주지 않을 거야.',
    avatar: '🧛',
    avatarImage: '/characters/ren.jpeg',
    coverImage: '/covers/ren.jpg',
    tags: ['뱀파이어', '다크', '영원'],
    affinity: 0,
    genre: 'fantasy',
    isPremium: true,
  },
  {
    id: 'char-ceo-yujin',
    name: '유진',
    nameEn: 'Yujin',
    age: 28,
    personality: '냉철한 CEO',
    description: '대한민국 톱3 IT 기업의 최연소 CEO. 완벽한 포커페이스 뒤에 숨겨진 외로움을 당신만이 알아챘다.',
    greeting: '......회의 끝났는데 아직 안 갔어? 커피 한 잔만. 딱 10분만 네 시간을 빌릴게.',
    avatar: '👔',
    avatarImage: '/characters/yujin.jpeg',
    coverImage: '/covers/yujin.jpg',
    tags: ['CEO', '차가움', '비밀'],
    affinity: 0,
    genre: 'romance',
    isPremium: true,
  },
];
